name: Build and Publish Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: midpoint-builder
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        run: |
          BASE_REVISION=`grep "ARG BASE_REVISION" Dockerfile | cut -d "=" -f 2 | sed "s/^v//"`
          RELEASE_REVISION=`grep "ARG RELEASE_REVISION" Dockerfile | cut -d "=" -f 2`
          IMAGE_TAG=${BASE_REVISION}-${RELEASE_REVISION}
          FULL_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}

          echo "Building $FULL_IMAGE_NAME:$IMAGE_TAG"

          docker build -t ${FULL_IMAGE_NAME}:${IMAGE_TAG} .
          docker push ${FULL_IMAGE_NAME}:${IMAGE_TAG}

